<a href="https://colab.research.google.com/github/DevP-ai/Mathematics-for-ML/blob/main/Lec_2(Matrix)_Essential_Maths_For_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
a=np.array([[1,7],[2,1],[3,2]])
print("Matrix A: \n",a)

Matrix A: 
 [[1 7]
 [2 1]
 [3 2]]


In [10]:
b=np.array([[1,1],[1,-1],[1,0]])
print("Matrix B: \n",b)

Matrix B: 
 [[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [11]:
c=np.add(a,b)
print("Addition of Two Matrices A+B: \n",c)

Addition of Two Matrices A+B: 
 [[2 8]
 [3 0]
 [4 2]]


In [12]:
d=np.subtract(a,b)
print("Substraction of Two Matrices A-B: \n",d)

Substraction of Two Matrices A-B: 
 [[0 6]
 [1 2]
 [2 2]]


In [16]:
r=np.array([[1,3,1],[1,0,1]])
m=np.dot(a,r)
print("Multriplication A.R: \n",m)

Multriplication A.R: 
 [[8 3 8]
 [3 6 3]
 [5 9 5]]


In [20]:
det=np.linalg.det(m)
print("Determinant of M: ",det)

Determinant of M:  0.0


Determinant is zero means m is a singular matrix,so m does not have Inverse 

In [23]:
e=np.array([[2,5],[4,8]])
print("Matrics E: \n",e)
inv=np.linalg.inv(e)
print("Inverse of A Matrix E: \n",inv)

Matrics E: 
 [[2 5]
 [4 8]]
Inverse of A Matrix E: 
 [[-2.    1.25]
 [ 1.   -0.5 ]]
